image: ocaml/opam2:latest

before_script:
  - sudo apt-get install m4
  - opam init
  - eval `opam config env`
  - opam update
  - opam install dune odoc

pages:
  stage: deploy
  script:
  - dune build @doc
  artifacts:
    paths:
    - _build/default/_doc/_html
  only:
  - master