image: ocaml/opam2:latest

before_script:
  - sudo apt-get -y install m4 pkg-config libssl-dev libffi-dev
  - opam init
  - eval `opam config env`
  - opam update
  - opam pin add ppx_deriving_yojson https://github.com/ocaml-ppx/ppx_deriving_yojson.git#82bc0b8
  - opam pin add -d disml .

pages:
  stage: deploy
  script:
  - dune build @doc
  - cp -r _build/default/_doc/_html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
  except:
  - merge_requests